[env]
RUST_LOG = "info"

[profiles]
env_files = [
    { file = ".env", profile = "development" },
]

[tasks.db-migrate]
command = "cargo"
args = ["sqlx", "migrate", "run"]

[tasks.db-create]
command = "cargo"
args = ["sqlx", "database", "create"]

[tasks.db-prepare]
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.db-verify]
command = "cargo"
args = ["sqlx", "prepare", "--check"]
